//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM2017.EventosServicios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EventosServicios.IEventos")]
    public interface IEventos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosSelect", ReplyAction="http://tempuri.org/IEventos/EventosSelectResponse")]
        System.Data.DataTable EventosSelect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosSelect", ReplyAction="http://tempuri.org/IEventos/EventosSelectResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> EventosSelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosDesactivadosSelect", ReplyAction="http://tempuri.org/IEventos/EventosDesactivadosSelectResponse")]
        System.Data.DataTable EventosDesactivadosSelect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosDesactivadosSelect", ReplyAction="http://tempuri.org/IEventos/EventosDesactivadosSelectResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> EventosDesactivadosSelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosTerminadosSelect", ReplyAction="http://tempuri.org/IEventos/EventosTerminadosSelectResponse")]
        System.Data.DataTable EventosTerminadosSelect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosTerminadosSelect", ReplyAction="http://tempuri.org/IEventos/EventosTerminadosSelectResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> EventosTerminadosSelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosSelectById", ReplyAction="http://tempuri.org/IEventos/EventosSelectByIdResponse")]
        System.Data.DataTable EventosSelectById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosSelectById", ReplyAction="http://tempuri.org/IEventos/EventosSelectByIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> EventosSelectByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosDetalleSelect", ReplyAction="http://tempuri.org/IEventos/EventosDetalleSelectResponse")]
        System.Data.DataTable EventosDetalleSelect(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventosDetalleSelect", ReplyAction="http://tempuri.org/IEventos/EventosDetalleSelectResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> EventosDetalleSelectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoInsert", ReplyAction="http://tempuri.org/IEventos/EventoInsertResponse")]
        string EventoInsert(CM2017.Propiedades.Eventos item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoInsert", ReplyAction="http://tempuri.org/IEventos/EventoInsertResponse")]
        System.Threading.Tasks.Task<string> EventoInsertAsync(CM2017.Propiedades.Eventos item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoUpdate", ReplyAction="http://tempuri.org/IEventos/EventoUpdateResponse")]
        int EventoUpdate(CM2017.Propiedades.Eventos item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoUpdate", ReplyAction="http://tempuri.org/IEventos/EventoUpdateResponse")]
        System.Threading.Tasks.Task<int> EventoUpdateAsync(CM2017.Propiedades.Eventos item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoDesactivar", ReplyAction="http://tempuri.org/IEventos/EventoDesactivarResponse")]
        void EventoDesactivar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoDesactivar", ReplyAction="http://tempuri.org/IEventos/EventoDesactivarResponse")]
        System.Threading.Tasks.Task EventoDesactivarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoReactivar", ReplyAction="http://tempuri.org/IEventos/EventoReactivarResponse")]
        bool EventoReactivar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/EventoReactivar", ReplyAction="http://tempuri.org/IEventos/EventoReactivarResponse")]
        System.Threading.Tasks.Task<bool> EventoReactivarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/TerminarEvento", ReplyAction="http://tempuri.org/IEventos/TerminarEventoResponse")]
        void TerminarEvento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventos/TerminarEvento", ReplyAction="http://tempuri.org/IEventos/TerminarEventoResponse")]
        System.Threading.Tasks.Task TerminarEventoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventosChannel : CM2017.EventosServicios.IEventos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventosClient : System.ServiceModel.ClientBase<CM2017.EventosServicios.IEventos>, CM2017.EventosServicios.IEventos {
        
        public EventosClient() {
        }
        
        public EventosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable EventosSelect() {
            return base.Channel.EventosSelect();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EventosSelectAsync() {
            return base.Channel.EventosSelectAsync();
        }
        
        public System.Data.DataTable EventosDesactivadosSelect() {
            return base.Channel.EventosDesactivadosSelect();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EventosDesactivadosSelectAsync() {
            return base.Channel.EventosDesactivadosSelectAsync();
        }
        
        public System.Data.DataTable EventosTerminadosSelect() {
            return base.Channel.EventosTerminadosSelect();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EventosTerminadosSelectAsync() {
            return base.Channel.EventosTerminadosSelectAsync();
        }
        
        public System.Data.DataTable EventosSelectById(string id) {
            return base.Channel.EventosSelectById(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EventosSelectByIdAsync(string id) {
            return base.Channel.EventosSelectByIdAsync(id);
        }
        
        public System.Data.DataTable EventosDetalleSelect(string id) {
            return base.Channel.EventosDetalleSelect(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EventosDetalleSelectAsync(string id) {
            return base.Channel.EventosDetalleSelectAsync(id);
        }
        
        public string EventoInsert(CM2017.Propiedades.Eventos item) {
            return base.Channel.EventoInsert(item);
        }
        
        public System.Threading.Tasks.Task<string> EventoInsertAsync(CM2017.Propiedades.Eventos item) {
            return base.Channel.EventoInsertAsync(item);
        }
        
        public int EventoUpdate(CM2017.Propiedades.Eventos item) {
            return base.Channel.EventoUpdate(item);
        }
        
        public System.Threading.Tasks.Task<int> EventoUpdateAsync(CM2017.Propiedades.Eventos item) {
            return base.Channel.EventoUpdateAsync(item);
        }
        
        public void EventoDesactivar(string id) {
            base.Channel.EventoDesactivar(id);
        }
        
        public System.Threading.Tasks.Task EventoDesactivarAsync(string id) {
            return base.Channel.EventoDesactivarAsync(id);
        }
        
        public bool EventoReactivar(string id) {
            return base.Channel.EventoReactivar(id);
        }
        
        public System.Threading.Tasks.Task<bool> EventoReactivarAsync(string id) {
            return base.Channel.EventoReactivarAsync(id);
        }
        
        public void TerminarEvento() {
            base.Channel.TerminarEvento();
        }
        
        public System.Threading.Tasks.Task TerminarEventoAsync() {
            return base.Channel.TerminarEventoAsync();
        }
    }
}
